name: Migrate DB
on:
  push:
    branches: main
    paths:
      - "db/**"
      - ".github/workflows/db.yaml"

env:
  AWS_ACCESS_KEY_ID: \${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: \${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  DB_PASSWORD: \${{ secrets.MYSQL_PASSWORD }}
  DB_USER: thankyou_directory
  DB_NAME: thankyou_directory
  RDS_ID: vargas-arts

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: install
        run: npm install
      - name: migrate
        run: npm run migrate